from enum import Enum


class FormatTournoi(Enum):
    ELIMINATION_SIMPLE = "ELIMINATIONSIMPLE"
    TOURNOI_A_LA_RONDE = "TOURNOI_A_LA_RONDE"
    ELIMINATION_SIMPLE_SPECIAL = "ELIMINATION_SIMPLE_SPECIAL"
    ELIMINATION_SIMPLE_POULE = "ELIMINATION_SIMPLE_POULE"


FormatTournoi = Enum(FormatTournoi, ["ELIMINATION_SIMPLE", "TOURNOI_A_LA_RONDE", "ELIMINATION_SIMPLE_SPECIAL", "ELIMINATION_SIMPLE_POULE"])
